### ISSUE TITLE
Add a /health that tests connection to the various databases

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/search-a-licious#55] opened 2023-09-26 08:01 UTC
In Folksonomy Engine API we have either:
* `/` leading to answer `{ "message": "Hello folksonomy World! Tip: open /docs for documentation" }`
* `/ping` which answers `{ "ping": "pong @ 2023-09-26 07:49:10.842300" }`

See:
* https://api.folksonomy.openfoodfacts.org/docs
* https://github.com/openfoodfacts/folksonomy_api/blob/main/folksonomy/api.py

**Comment by alexgarel** [comment] 2023-10-10 08:25
It's even better to add a /health that test connection to the various databases. Like for robotoff https://robotoff.openfoodfacts.org/api/v1/health

**Comment by teolemon** [comment] 2024-05-07 19:28
Duplicate of #67

**Closed by teolemon** 2024-05-07 19:28 UTC
Labels: ✨ enhancement, monitoring
